Src/Magicodes.WeiChat/Controllers/WeChat/KeyWords/WeiChat_KeyWordAutoReplyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using Magicodes.WeiChat.Infrastructure.MvcExtension.Ajax;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;
using Magicodes.WeiChat.Data;
using Magicodes.WeiChat.Data.Models.WeiChat;
using Magicodes.WeiChat.Unity;
namespace Magicodes.WeiChat.Controllers.WeChat.KeyWords
{
    [Authorize]
    public class WeiChat_KeyWordAutoReplyController : TenantBaseController<WeiChat_KeyWordAutoReply>
    {

        // GET: WeiChat_KeyWordAutoReplay
        public async Task<ActionResult> Index(string q, int pageIndex = 1, int pageSize = 10)
        {
            var queryable = db.WeiChat_KeyWordAutoReplies.Include(w => w.CreateUser).Include(w => w.UpdateUser);
            if (!string.IsNullOrWhiteSpace(q))
            {
                //请替换为相应的搜索逻辑
                queryable = queryable.Where(p => p.KeyWord.Contains(q));
            }
            var currentItems = await queryable.OrderByDescending(p => p.CreateTime).Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync();
            var pagedList = new PagedList<WeiChat_KeyWordAutoReply>(currentItems, pageIndex, pageSize, queryable.Count());
            return View(pagedList);
        }

        // GET: WeiChat_KeyWordAutoReplay/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WeiChat_KeyWordAutoReply weiChat_KeyWordAutoReplay = await db.WeiChat_KeyWordAutoReplies.FindAsync(id);
            if (weiChat_KeyWordAutoReplay == null)
            {
                return HttpNotFound();
            }
            return View(weiChat_KeyWordAutoReplay);
        }

        // GET: WeiChat_KeyWordAutoReplay/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WeiChat_KeyWordAutoReplay/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Create([Bind(Include = "Id,KeyWord,MatchType,KeyWordContentType,AllowEventKey,ContentId")] WeiChat_KeyWordAutoReply weiChat_KeyWordAutoReplay)
        {
            if (ModelState.IsValid)
            {
                if (db.WeiChat_KeyWordAutoReplies.Any(p => p.TenantId == TenantId && p.KeyWord == weiChat_KeyWordAutoReplay.KeyWord))
                {
                    ModelState.AddModelError("KeyWord", "关键字重复，请重新输入！");
                    return View(weiChat_KeyWordAutoReplay);
                }
                switch (weiChat_KeyWordAutoReplay.KeyWordContentType)
                {
                    case KeyWordContentTypes.Text:
                        break;
                    case KeyWordContentTypes.Image:
                        {
                            var mediaId = Request.Form["mediaId"];
                            if (string.IsNullOrEmpty(mediaId))
                            {
                                ModelState.AddModelError("", "您没有选择资源，请选择资源！");
                                return View(weiChat_KeyWordAutoReplay);
                            }
                            var image = new WeiChat_KeyWordImageContent()
                            {
                                ImageMediaId = mediaId,
                            };
                            SetModelWithSaveChanges(image, default(Guid));
                            weiChat_KeyWordAutoReplay.ContentId = image.Id;
                        }
                        break;
                    case KeyWordContentTypes.Voice:
                        {
                            var mediaId = Request.Form["mediaId"];
                            if (string.IsNullOrEmpty(mediaId))
                            {
                                ModelState.AddModelError("", "您没有选择资源，请选择资源！");
                                return View(weiChat_KeyWordAutoReplay);
                            }
                            var model = new WeiChat_KeyWordVoiceContent()
                            {
                                VoiceMediaId = mediaId,
                            };
                            SetModelWithSaveChanges(model, default(Guid));
                            weiChat_KeyWordAutoReplay.ContentId = model.Id;
                            break;
                        }
                    case KeyWordContentTypes.Video:
                        {
                            var mediaId = Request.Form["mediaId"];
                            if (string.IsNullOrEmpty(mediaId))
                            {
                                ModelState.AddModelError("", "您没有选择资源，请选择资源！");
                                return View(weiChat_KeyWordAutoReplay);
                            }
                            var model = new WeiChat_KeyWordVideoContent()
                            {
                                MediaId = mediaId,
                            };
                            SetModelWithSaveChanges(model, default(Guid));
                            weiChat_KeyWordAutoReplay.ContentId = model.Id;
                            break;
                        }
                    case KeyWordContentTypes.News:
                        break;
                    default:
                        break;
                }
                SetModel(weiChat_KeyWordAutoReplay, default(Guid));
                db.WeiChat_KeyWordAutoReplies.Add(weiChat_KeyWordAutoReplay);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(weiChat_KeyWordAutoReplay);
        }

        // GET: WeiChat_KeyWordAutoReplay/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WeiChat_KeyWordAutoReply weiChat_KeyWordAutoReplay = await db.WeiChat_KeyWordAutoReplies.FindAsync(id);
            if (weiChat_KeyWordAutoReplay == null)
            {
                return HttpNotFound();
            }
            return View(weiChat_KeyWordAutoReplay);
        }

        // POST: WeiChat_KeyWordAutoReplay/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit([Bind(Include = "Id,KeyWord,AllowEventKey,MatchType,KeyWordContentType,ContentId,AppId")] WeiChat_KeyWordAutoReply weiChat_KeyWordAutoReply)
        {
            if (ModelState.IsValid)
            {
                SetModel(weiChat_KeyWordAutoReply, weiChat_KeyWordAutoReply.Id);
                var oldValues = db.Entry(weiChat_KeyWordAutoReply).GetDatabaseValues();
                if (oldValues.GetValue<string>("KeyWord") != weiChat_KeyWordAutoReply.KeyWord && db.WeiChat_KeyWordAutoReplies.Any(p => p.TenantId == TenantId && p.KeyWord == weiChat_KeyWordAutoReply.KeyWord))
                {
                    ModelState.AddModelError("KeyWord", "关键字重复，请重新输入！");
                    return View(weiChat_KeyWordAutoReply);
                }
                var oldContentId = oldValues.GetValue<Guid?>("ContentId");
                var oldType = oldValues.GetValue<KeyWordContentTypes>("KeyWordContentType");
                #region 更新回复内容
                switch (weiChat_KeyWordAutoReply.KeyWordContentType)
                {
                    case KeyWordContentTypes.Text:
                        break;
                    case KeyWordContentTypes.Image:
                        {
                            var mediaId = Request.Form["mediaId"];
                            if (string.IsNullOrEmpty(mediaId))
                            {
                                ModelState.AddModelError("", "您没有选择资源，请选择资源！");
                                return View(weiChat_KeyWordAutoReply);
                            }

                            var image = new WeiChat_KeyWordImageContent()
                            {
                                ImageMediaId = mediaId,
                            };
                            SetModelWithSaveChanges(image, default(Guid));
                            weiChat_KeyWordAutoReply.ContentId = image.Id;
                        }
                        break;
                    case KeyWordContentTypes.Voice:
                        {
                            var mediaId = Request.Form["mediaId"];
                            if (string.IsNullOrEmpty(mediaId))
                            {
                                ModelState.AddModelError("", "您没有选择资源，请选择资源！");
                                return View(weiChat_KeyWordAutoReply);
                            }
                            var model = new WeiChat_KeyWordVoiceContent()
                            {
                                VoiceMediaId = mediaId,
                            };
                            SetModelWithSaveChanges(model, default(Guid));
                            weiChat_KeyWordAutoReply.ContentId = model.Id;
                            break;
                        }
                    case KeyWordContentTypes.Video:
                        {
                            var mediaId = Request.Form["mediaId"];
                            if (string.IsNullOrEmpty(mediaId))
                            {
                                ModelState.AddModelError("", "您没有选择资源，请选择资源！");
                                return View(weiChat_KeyWordAutoReply);
                            }

                            var model = new WeiChat_KeyWordVideoContent()

Src/Magicodes.WeiChat/Views/WeiChat_KeyWordAutoReply/Create.cshtml
@using Magicodes.WeiChat.Unity;
@model Magicodes.WeiChat.Data.Models.WeiChat.WeiChat_KeyWordAutoReply

@{
    ViewBag.TwoTitle = "关键字回复";
}
@Html.Partial("_FormHead")

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <hr style="margin:2px 2px 10px 2px;" />

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                @Html.LabelFor(model => model.KeyWord, htmlAttributes: new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.KeyWord, new { htmlAttributes = new { @class = "form-control" } })
                                    @*<span class="help-block m-b-none">辅助性描述文字。</span>*@
                                    @Html.ValidationMessageFor(model => model.KeyWord, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.MatchType, htmlAttributes: new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EnumDropDownListFor(model => model.MatchType, htmlAttributes: new { @class = "form-control" })
                                    @*<span class="help-block m-b-none">辅助性描述文字。</span>*@
                                    @Html.ValidationMessageFor(model => model.MatchType, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.AllowEventKey, htmlAttributes: new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.AllowEventKey)
                                    <span class="help-block m-b-none">请确保菜单事件关键字和本关键字大小写一致，仅支持完全等于时触发。</span>
                                    @Html.ValidationMessageFor(model => model.AllowEventKey, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <content-choice-button params="contentId: ContentId,mediaId:MediaId,keyWordContentType:KeyWordContentType,contentTypes:Types"></content-choice-button>

                            <input type="hidden" name="KeyWordContentType" data-bind="value:KeyWordContentType" />
                            <input type="hidden" name="ContentId" data-bind="value:ContentId" />
                            <input type="hidden" name="MediaId" data-bind="value:MediaId" />

                            @Html.ValidationMessageFor(model => model.KeyWordContentType, "", new { @class = "text-danger" })
                            @Html.ValidationMessageFor(model => model.ContentId, "", new { @class = "text-danger" })

                            <div class="form-group">
                                <div class="col-md-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i>&nbsp;提交</button>
                                    <a href="@Url.Action("Index")" class="btn btn-primary"><i class="fa fa-mail-reply"></i>&nbsp;返回</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    @*请自行移除没用到的样式*@
    @*复选框样式*@
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @*日期控件样式*@
    @Styles.Render("~/plugins/dataPickerStyles")
}
@section Scripts{
    <script src="~/Scripts/app/components/content-choice.js"></script>
    @Scripts.Render("~/plugins/iCheck")
    <script>
        function ViewModel() {
            var self = this;
            this.KeyWordContentType = ko.observable('@(Model==null?1:(int)Model.KeyWordContentType)');
            this.ContentId = ko.observable('@(Model==null?"":Model.ContentId.ToString())');
            this.Types = ko.observableArray([]);
            this.MediaId = ko.observable('');
            this.init = function () {
                mwc.restApi.get({
                    url: '@Url.Action("GetKeyWordContentTypes", "WeiChat_KeyWordAutoReply")',
                    success: function (data) {
                        for (var name in data) {
                            self.Types().push({ text: name, value: data[name] });
                        }
                        //为了兼容IE、火狐等
                        ko.applyBindings(window.CurrentModel, document.getElementById('mainBody'));
                    }
                });
            };
            self.init();
        }
        $(function () {
            mwc.bs.init({
                //是否启用ICheck
                iCheck: true,
                //是否启用选择所有
                checkAll: false,
                //是否启用模式框链接触发
                modalClick: false,
                //是否启用批量操作
                batchOperation: false,
                //是否启用loadingButton
                loadingButton: false
            });
            window.CurrentModel = new ViewModel();
        });
    </script>
}

Src/Magicodes.WeiChat/Views/WeiChat_KeyWordAutoReply/Delete.cshtml
@model Magicodes.WeiChat.Data.Models.WeiChat.WeiChat_KeyWordAutoReply

@{
    ViewBag.TwoTitle = "关键字回复";
}
@Html.Partial("_FormHead")

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <hr style="margin:2px 2px 10px 2px;" />
                    @Html.Partial("_FormDetails", Model)

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-actions no-color">
                            <button type="button" class="btn btn-warning pull-right" id="btnDelete"><i class="fa fa-remove"></i>&nbsp;&nbsp;删除</button>
                            <br />
                            @Html.ActionLink("返回", "Index")
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
}
@section Scripts {
    @Scripts.Render("~/plugins/iCheck")
    <script type="text/javascript">
        $(function () {
            $("input[type=checkbox]").iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
            $('#btnDelete').on('click', function () {
                mwc.message.confirm("确定要删除么？", "警告", function (result) {
                    if (result) {
                        mwc.ui.setBusy();
                        $('form').submit();
                    }
                });
            });
        });
    </script>
}

Src/Magicodes.WeiChat/Views/WeiChat_KeyWordAutoReply/Details.cshtml
@model Magicodes.WeiChat.Data.Models.WeiChat.WeiChat_KeyWordAutoReply

@{
    ViewBag.TwoTitle = "关键字回复";
}
@Html.Partial("_FormHead")

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <hr style="margin:2px 2px 10px 2px;" />
                    @Html.Partial("_FormDetails",Model)
                    <p>
                        @Html.ActionLink("编辑", "Edit", new { id = Model.Id }) |
                        @Html.ActionLink("返回", "Index")
                    </p>
                </div>

            </div>
        </div>
    </div>
</div>
@section Styles {
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
}
@section Scripts {
    @Scripts.Render("~/plugins/iCheck")
    <script type="text/javascript">
        $(function () {
            $("input[type=checkbox]").iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });
    </script>
}

Src/Magicodes.WeiChat/Views/WeiChat_KeyWordAutoReply/Edit.cshtml
@using Magicodes.WeiChat.Unity;
@model Magicodes.WeiChat.Data.Models.WeiChat.WeiChat_KeyWordAutoReply

@{
    ViewBag.TwoTitle = "关键字回复";
}
@Html.Partial("_FormHead")
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <hr style="margin:2px 2px 10px 2px;" />
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()
                        
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.TenantId)
                            <div class="form-group">
                                @Html.LabelFor(model => model.KeyWord, htmlAttributes: new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.KeyWord, new { htmlAttributes = new { @class = "form-control" } })
                                    @*<span class="help-block m-b-none">辅助性描述文字。</span>*@
                                    @Html.ValidationMessageFor(model => model.KeyWord, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.MatchType, htmlAttributes: new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EnumDropDownListFor(model => model.MatchType, htmlAttributes: new { @class = "form-control" })
                                    @*<span class="help-block m-b-none">辅助性描述文字。</span>*@
                                    @Html.ValidationMessageFor(model => model.MatchType, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.AllowEventKey, htmlAttributes: new { @class = "control-label col-sm-2" })
                                <div class="col-sm-10">
                                    @Html.EditorFor(model => model.AllowEventKey)
                                    <span class="help-block m-b-none">请确保菜单事件关键字和本关键字大小写一致，仅支持完全等于时触发。</span>
                                    @Html.ValidationMessageFor(model => model.AllowEventKey, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <content-choice-button params="contentId: ContentId,mediaId:MediaId,keyWordContentType:KeyWordContentType,contentTypes:Types"></content-choice-button>

                            <input type="hidden" name="KeyWordContentType" data-bind="value:KeyWordContentType" />
                            <input type="hidden" name="ContentId" data-bind="value:ContentId" />
                            <input type="hidden" name="MediaId" data-bind="value:MediaId" />

                            @Html.ValidationMessageFor(model => model.KeyWordContentType, "", new { @class = "text-danger" })
                            @Html.ValidationMessageFor(model => model.ContentId, "", new { @class = "text-danger" })

                            <div class="form-group">
                                <div class="col-md-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i>&nbsp;提交</button>
                                    <a href="@Url.Action("Index")" class="btn btn-primary"><i class="fa fa-mail-reply"></i>&nbsp;返回</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    @*请自行移除没用到的样式*@
    @*复选框样式*@
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @*日期控件样式*@
    @Styles.Render("~/plugins/dataPickerStyles")
}
@section Scripts{
    <script src="~/Scripts/app/components/content-choice.js"></script>
    @Scripts.Render("~/plugins/iCheck")
    <script>
        function ViewModel() {
            var self = this;
            this.KeyWordContentType = ko.observable('@((int)Model.KeyWordContentType)');
            this.ContentId = ko.observable('@(Model.ContentId)');
            this.Types = ko.observableArray([]);
            this.MediaId = ko.observable('');
            this.init = function () {
                mwc.restApi.get({
                    url: '@Url.Action("GetKeyWordContentTypes", "WeiChat_KeyWordAutoReply")',
                    success: function (data) {
                        for (var name in data) {
                            self.Types().push({ text: name, value: data[name] });
                        }
                        //为了兼容IE、火狐等
                        ko.applyBindings(window.CurrentModel, document.getElementById('mainBody'));
                    }
                });
            };
            self.init();
        }
        $(function () {
            mwc.bs.init({
                //是否启用ICheck
                iCheck: true,
                //是否启用选择所有
                checkAll: false,
                //是否启用模式框链接触发
                modalClick: false,
                //是否启用批量操作
                batchOperation: false,
                //是否启用loadingButton
                loadingButton: false
            });
            window.CurrentModel = new ViewModel();
        });
    </script>
}

Src/Magicodes.WeiChat/Views/WeiChat_KeyWordAutoReply/_FormDetails.cshtml
@model Magicodes.WeiChat.Data.Models.WeiChat.WeiChat_KeyWordAutoReply
<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.KeyWord)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.KeyWord)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.CreateTime)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.CreateTime)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.UpdateTime)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.UpdateTime)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.MatchType)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.MatchType)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.KeyWordContentType)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.KeyWordContentType)
    </dd>

    <dt>
        @Html.DisplayNameFor(model => model.ContentId)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.ContentId)
    </dd>
</dl>