Src/Magicodes.WeiChat/Areas/SystemAdmin/Models/AppUsersViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Magicodes.WeiChat.Areas.SystemAdmin.Models
{
    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "用户名")]
        public string UserName { get; set; }
        [Required]
        [MaxLength(200)]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "邮箱")]
        public string Email { get; set; }
        
        [MaxLength(20)]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "手机")]
        public string PhoneNumber { get; set; }

        [Required]
        [StringLength(100, MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "密码")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "确认密码")]
        [Compare("Password", ErrorMessage = "确认密码不匹配！")]
        public string ConfirmPassword { get; set; }
        [Required]
        [Display(Name = "租户")]
        public int TenantId { get; set; }
    }

    public class ChangePasswordViewModel
    {
        public string Id { get; set; }
        [Required]
        [Display(Name = "用户名")]
        public string UserName { get; set; }
        [Required]
        [MaxLength(200)]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "邮箱")]
        public string Email { get; set; }

       
        [Required]
        [StringLength(100, MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "密码")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "确认密码")]
        [Compare("Password", ErrorMessage = "确认密码不匹配！")]
        public string ConfirmPassword { get; set; }
        
    }
}

Src/Magicodes.WeiChat/Areas/SystemAdmin/Controllers/AppUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Magicodes.WeiChat.Areas.SystemAdmin.Models;
using Magicodes.WeiChat.Controllers;
using Webdiyer.WebControls.Mvc;
using Magicodes.WeiChat.Data;
using Magicodes.WeiChat.Data.Models;
using Magicodes.WeiChat.Infrastructure.Identity;
using Microsoft.AspNet.Identity;
using Magicodes.WeiChat.Infrastructure.MvcExtension.Ajax;
using Microsoft.Owin.Security;
using Magicodes.Mvc.RoleMenuFilter;

namespace Magicodes.WeiChat.Areas.SystemAdmin.Controllers
{
    public class AppUsersController : SystemAdminBase<WeiChat_App, int>
    {
        IdentityManager _identityMangaer = new IdentityManager();
        public AppUserManager UserManager
        {
            get
            {
                return _identityMangaer.UserManager;
            }

        }
        [RoleMenuFilter("租户成员管理", "F4DF1F7A-32D6-408F-B8BA-4171531E4E16", "Admin", url: "/SystemAdmin/AppUsers",
             parentId: "A1199F15-8859-425D-9148-B0D85F4272F2", tag: "System")]
        // GET: AppUsers
        public async Task<ActionResult> Index(string q, int? tenantId = null, int? check = null, string roleId = null, int pageIndex = 1, int pageSize = 20)
        {
            var queryable = UserManager.Users;
            if (tenantId != null)
            {
                queryable = queryable.Where(p => p.TenantId == tenantId);
            }
            else
            {
                //如果是系统管理员
                if (!db.Account_Tenants.Any(p => p.Id == UserTenantId && p.IsSystemTenant))
                {
                    throw new Exception("您没有权限进行相关操作！");
                }
            }
            if (!string.IsNullOrEmpty(roleId))
            {
                if (check != null)
                {
                    queryable = queryable.Where(p => !p.Roles.Any(p1 => p1.RoleId == roleId));
                }
                else
                    queryable = queryable.Where(p => p.Roles.Any(p1 => p1.RoleId == roleId));
            }
            if (!string.IsNullOrWhiteSpace(q))
            {
                //请替换为相应的搜索逻辑
                queryable = queryable.Where(p => p.Email.Contains(q) || p.PhoneNumber.Contains(q) || p.UserName.Contains(q));
            }
            var pagedList = new PagedList<AppUser>(
                             await queryable.OrderBy(p => p.Id)
                             .Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync(),
                             pageIndex, pageSize, await queryable.CountAsync());
            return View(pagedList);
        }
        // GET: AppUsers/Bind
        public ActionResult Bind(string id)
        {
            AppUser appUser = UserManager.FindById(id);
            if (appUser == null)
            {
                return HttpNotFound();
            }
            var qrCode = db.WeiChat_QRCodes.FirstOrDefault(p => p.ParamsValue == id && p.UserFor == Data.Models.WeiChat.QRCodeUseForTypes.BindManager);
            if (qrCode == null)
            {
                var result = Magicodes.WeChat.SDK.WeChatApisContext.Current.QrCodeApi.CreateByStringValue(id);
                if (result.IsSuccess())
                {
                    qrCode = new Data.Models.WeiChat.WeiChat_QRCode()
                    {
                        CreateBy = appUser.Id,
                        CreateTime = DateTime.Now,
                        ExpireSeconds = 0,
                        ParamsValue = id,
                        TenantId = appUser.TenantId,
                        Ticket = result.Ticket,
                        UserFor = Data.Models.WeiChat.QRCodeUseForTypes.BindManager,
                        Remark = "绑定微信管理员"
                    };
                    db.WeiChat_QRCodes.Add(qrCode);
                    db.SaveChanges();
                }
            }
            return View(qrCode);
        }

        // GET: AppUsers/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppUser appUser = await UserManager.FindByIdAsync(id);
            if (appUser == null)
            {
                return HttpNotFound();
            }
            return View(appUser);
        }

        // GET: AppUsers/Create
        public ActionResult Create(int? tenantId = null)
        {
            ViewBag.TenantId = new SelectList(db.Account_Tenants.ToList(), "Id", "Name", tenantId);
            return View();
        }

        // POST: AppUsers/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var userManager = new UserManager<AppUser, string>(new AppUserStore(new AppDbContext())
                {
                    TenantId = model.TenantId
                });
                await userManager.CreateAsync(new AppUser()
                {
                    Id = Guid.NewGuid().ToString("N"),
                    UserName = model.UserName,
                    Email = model.Email,
                    TenantId = model.TenantId,
                    PhoneNumber = model.PhoneNumber
                }, model.Password);
                return RedirectToAction("Index", new { tenantId = model.TenantId });
            }
            ViewBag.TenantId = new SelectList(db.Account_Tenants.ToList(), "Id", "Name", model.TenantId);
            return View(model);
        }

        // GET: AppUsers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppUser appUser = db.Users.FirstOrDefault(p => p.Id == id);
            if (appUser == null)
            {
                return HttpNotFound();
            }
            ViewBag._TenantId = appUser.TenantId;
            ViewBag.TenantId = new SelectList(db.Account_Tenants.ToList(), "Id", "Name", appUser.TenantId);
            return View(appUser);
        }

        // POST: AppUsers/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,OpenId,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName,TenantId")] AppUser appUser)
        {
            if (ModelState.IsValid)
            {
                var oldUser = await db.Users.FirstAsync(p => p.Id == appUser.Id);
                //UserManager.ChangePhoneNumberAsync()
                oldUser.OpenId = appUser.OpenId;
                oldUser.Email = appUser.Email;
                //oldUser.UserName
                oldUser.PhoneNumber = appUser.PhoneNumber;
                oldUser.TwoFactorEnabled = appUser.TwoFactorEnabled;
                oldUser.TenantId = appUser.TenantId;
                await db.SaveChangesAsync();
                return RedirectToAction("Index", new { tenantId = oldUser.TenantId });
            }
            ViewBag.TenantId = new SelectList(db.Account_Tenants.ToList(), "Id", "Name", appUser.TenantId);
            return View(appUser);
        }
        public async Task<ActionResult> ChangePassword(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var appUser = await UserManager.FindByIdAsync(id);
            if (appUser == null)
            {
                return HttpNotFound();
            }
            var model = new ChangePasswordViewModel()
            {
                Email = appUser.Email,
                UserName = appUser.UserName,
                Id = appUser.Id
            };
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            var appUser = await UserManager.FindByIdAsync(model.Id);
            if (appUser == null)
            {
                return HttpNotFound();
            }
            var userManager = new UserManager<AppUser, string>(new AppUserStore(new AppDbContext())
            {
                TenantId = appUser.TenantId
            });
            //先移除密码，再加上密码
            var result = await userManager.RemovePasswordAsync(model.Id);
            if (result.Succeeded)
            {
                result = await userManager.AddPasswordAsync(model.Id, model.Password);
            }
            if (result.Succeeded)
            {
                return RedirectToAction("Index", new { tenantId = appUser.TenantId });
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error);
                }
            }
            return View(model);
        }
        // GET: AppUsers/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppUser appUser = await UserManager.FindByIdAsync(id);
            if (appUser == null)
            {
                return HttpNotFound();
            }
            //至少需要保存一个管理员账户
            if (db.Users.Count(p => p.TenantId == appUser.TenantId) == 1 && db.Account_Tenants.Count(p => p.Id == appUser.TenantId && p.IsSystemTenant) == 1)
            {

Src/Magicodes.WeiChat/Controllers/SystemManager/AppUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Webdiyer.WebControls.Mvc;
using Magicodes.WeiChat.Data;
using Magicodes.WeiChat.Data.Models;
using Magicodes.WeiChat.Infrastructure.Identity;

namespace Magicodes.WeiChat.Controllers.SystemManager
{
    public class AppUsersController : BaseController
    {
        IdentityManager _identityManager = new IdentityManager();
        public AppUserManager UserManager
        {
            get
            {
                return _identityManager.UserManager;
            }

        }
        // GET: AppUsers
        public async Task<ActionResult> Index(string q, int pageIndex = 1, int pageSize = 20)
        {
            var queryable = UserManager.Users;
            //如果是系统管理员
            if (db.Account_Tenants.Any(p => p.Id == UserTenantId && p.IsSystemTenant))
            {

            }
            else
            {
                queryable = queryable.Where(p => p.TenantId == UserTenantId);
            }
            if (!string.IsNullOrWhiteSpace(q))
            {
                //请替换为相应的搜索逻辑
                queryable = queryable.Where(p => p.OpenId.Contains(q) || p.Email.Contains(q) || p.PasswordHash.Contains(q) || p.SecurityStamp.Contains(q) || p.PhoneNumber.Contains(q) || p.UserName.Contains(q));
            }
            var pagedList = new PagedList<AppUser>(
                             await queryable.OrderBy(p => p.Id)
                             .Skip((pageIndex - 1) * pageSize).Take(pageSize).ToListAsync(),
                             pageIndex, pageSize, await queryable.CountAsync());
            return View(pagedList);
        }

        // GET: AppUsers/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppUser appUser = await UserManager.FindByIdAsync(id);
            if (appUser == null)
            {
                return HttpNotFound();
            }
            return View(appUser);
        }

        
        // GET: AppUsers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AppUsers/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,OpenId,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] AppUser appUser)
        {
            if (ModelState.IsValid)
            {
                db.Users.Add(appUser);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(appUser);
        }

        // GET: AppUsers/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppUser appUser = await UserManager.FindByIdAsync(id);
            if (appUser == null)
            {
                return HttpNotFound();
            }
            return View(appUser);
        }

        // POST: AppUsers/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,OpenId,Email,EmailConfirmed,PasswordHash,SecurityStamp,PhoneNumber,PhoneNumberConfirmed,TwoFactorEnabled,LockoutEndDateUtc,LockoutEnabled,AccessFailedCount,UserName")] AppUser appUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appUser).State = System.Data.Entity.EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(appUser);
        }

        // GET: AppUsers/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppUser appUser = await UserManager.FindByIdAsync(id);
            if (appUser == null)
            {
                return HttpNotFound();
            }
            //至少需要保存一个管理员账户
            if (db.Account_Tenants.Count(p => p.Id == appUser.TenantId && p.IsSystemTenant) == 1)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "至少需要保留一个管理员账户！");
            }
            return View(appUser);
        }

        // POST: AppUsers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            AppUser appUser = await UserManager.FindByIdAsync(id);
            db.Users.Remove(appUser);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Src/Magicodes.WeiChat/Areas/SystemAdmin/Views/AppUsers/Bind.cshtml
@model Magicodes.WeiChat.Data.Models.WeiChat.WeiChat_QRCode

@{
    ViewBag.Title = "绑定微信管理员";
}

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <hr style="margin:2px 2px 10px 2px;" />
                    <div>
                        <img width="400" height="400" src="@Magicodes.WeChat.SDK.WeChatApisContext.Current.QrCodeApi.GetQrCodeUrl(Model.Ticket)" />
                    </div>
                    <div>请扫描以上二维码绑定管理员</div>
                </div>
                <p>
                    @Html.ActionLink("返回", "Index")
                </p>
            </div>
        </div>
    </div>
</div>

Src/Magicodes.WeiChat/Areas/SystemAdmin/Views/AppUsers/Index.cshtml
@using Webdiyer.WebControls.Mvc;
@model PagedList<Magicodes.WeiChat.Data.Models.AppUser>

@{
    ViewBag.Title = "租户成员管理";
}
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <hr style="margin:2px 2px 10px 2px;" />
                    <div class="row">
                        <div class="col-sm-3">
                            @using (Html.BeginForm("Index", @Request.RequestContext.RouteData.GetRequiredString("controller"), FormMethod.Get))
                            {

                                <input type="hidden" name="roleId" value="@Request.QueryString["roleId"]" />
                                if (!string.IsNullOrEmpty(Request.QueryString["tenantId"]))
                                {
                                    <input type="hidden" name="tenantId" value="@Request.QueryString["tenantId"]" />
                                }
                                if (!string.IsNullOrEmpty(Request.QueryString["check"]))
                                {
                                    <input type="hidden" name="check" value="@Request.QueryString["check"]" />
                                }
                                <div class="input-group">
                                    @Html.TextBox("q", ViewBag.q as string, new { @placeholder = "请输入关键字", @class = "input-sm form-control" })
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-search"></i>&nbsp;搜索</button>
                                    </span>
                                </div>
                            }
                        </div>
                        @if (string.IsNullOrEmpty(Request.QueryString["check"]))
                        {
                            if (!string.IsNullOrEmpty(Request.QueryString["roleId"]))
                            {
                                <a class="btn btn-warning btn-sm" id="btnAdd" href="javascript:void(0)" data-title="添加成员" data-url="@Url.Action("Index","AppUsers", new { roleId = Request.QueryString["roleId"] ,lightLayout=1,check=1})" data-clicktype="modal"><i class="fa fa-plus"></i>&nbsp;添加</a>
                            }
                            else
                            {
                                <a class="btn btn-primary btn-sm" href="@Url.Action("Create",new { tenantId=Request.QueryString["tenantId"]})" id="btnAdd"><i class="fa fa-plus"></i>&nbsp;新建</a>
                            }
                        }
                        else
                        {
                            <a class="btn btn-warning btn-sm" id="btnOk" data-action="AddUsersToRole" data-param="@Request.QueryString["roleId"]" data-reloadparent="true"><i class="fa fa-plus"></i>&nbsp;确定添加</a>
                        }
                    </div>
                    <div>
                        <table class="table table-striped table-bordered table-hover" style="overflow-x:scroll">
                            <tr>
                                @if (!string.IsNullOrEmpty(Request.QueryString["check"]))
                                {
                                    <th>
                                        <input type="checkbox" name="checkAll" id="chkCheckAll" class="i-checks" />
                                    </th>
                                }

                                <th>
                                    @Html.DisplayNameFor(model => model.UserName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.OpenId)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Email)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.PhoneNumber)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.LockoutEndDateUtc)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.LockoutEnabled)
                                </th>
                                @if (string.IsNullOrEmpty(Request.QueryString["check"]))
                                {
                                    <th></th>
                                }

                            </tr>

                            @foreach (var item in Model)
                            {
                                <tr>
                                    @if (!string.IsNullOrEmpty(Request.QueryString["check"]))
                                    {
                                        <td>
                                            <input type="checkbox" name="ids" class="i-checks" value="@(item.Id)" />
                                        </td>
                                    }
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UserName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.OpenId)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Email)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LockoutEndDateUtc)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.LockoutEnabled)
                                    </td>
                                    @if (string.IsNullOrEmpty(Request.QueryString["check"]))
                                    {
                                        <td>
                                            <div class="btn-group">
                                                <a href="@Url.Action("Details", new { id=item.Id})" class="btn btn-white">查看</a>
                                                <a href="@Url.Action("ChangePassword", new { id=item.Id})" class="btn btn-white">修改密码</a>
                                                <a href="@Url.Action("Bind", new { id=item.Id})" class="btn btn-white">绑定微信</a>
                                                <a class="btn btn-white" data-clicktype='modal' data-title="角色设置" data-url="@Url.Action("Roles", new { userId = item.Id })">角色设置</a>
                                                <button data-toggle="dropdown" class="btn btn-white dropdown-toggle">更多操作 <span class="caret"></span></button>
                                                <ul class="dropdown-menu">
                                                    <li>@Html.ActionLink("编辑", "Edit", new { id = item.Id })</li>
                                                    <li>@Html.ActionLink("删除", "Delete", new { id = item.Id })</li>
                                                    @*分割线*@
                                                    @*<li class="divider"></li>*@
                                                </ul>
                                            </div>
                                        </td>
                                    }
                                </tr>
                            }
                        </table>
                    </div>
                    <div class="row">
                        @Html.Partial("_BootStrapPager", Model)
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Styles {
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
}
@section Scripts {
    @Scripts.Render("~/plugins/iCheck")
    <script type="text/javascript">
        function batchOperation(operation, comfirmMessage, param, reloadParent) {
            var $checkInputs = $("input[type=checkbox][name=ids]:checked");
            if ($checkInputs.length === 0) {
                mwc.message.warn("请至少选择一项！");
                return;
            }
            function post() {
                var ids = new Array();
                $.each($("input[type=checkbox][name=ids]:checked").serializeArray(), function (i, v) {
                    ids.push(v.value);
                });
                var apiData = { ids: ids };
                if (param)
                    apiData.param = param;

                mwc.restApi.post({
                    url: '@Request.RequestContext.RouteData.GetRequiredString("controller")/BatchOperation/' + operation,
                    contentType: "application/x-www-form-urlencoded",
                    data: apiData,
                    success: function (data) {
                        console.debug(reloadParent);
                        if (reloadParent)
                            parent.location.reload();
                        else
                            location.reload();
                    }
                });
            }
            if (comfirmMessage) {
                mwc.message.confirm("", comfirmMessage, function (isConfirmed) {
                    isConfirmed && post();
                });
            } else {
                post();
            }

        }
        $(function () {
            $('input[type=checkbox]').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green'
            });
            $("#chkCheckAll").on('ifToggled', function (e) {
                $("input[type=checkbox][name=ids]").iCheck(e.currentTarget.checked ? "check" : "uncheck");
            });
            //将clicktype='modal'属性的链接均用弹窗打开
            $("a[data-clicktype='modal']").on('click', function () {
                var url = $(this).data('url');
                var title = $(this).data('title');
                mwc.window.show(title, url);
            });
            //批量操作
            $("#toolBar button[data-action],a[data-action]").on('click', function () {
                batchOperation($(this).data("action"), $(this).data("comfirmmessage"), $(this).data("param"), $(this).data("reloadparent"));
            });
        });
    </script>
}